### ISSUE TITLE
vCenter version compatibility list

### ISSUE THREAD

**Issue by DustinTrap** [napalm255/ansible-vmware_drs#31]
This is a great script and solves a problem we're facing. Can you provide a list of what vCenter versions you think this will work on?

**Comment by napalm255** [comment]
So, it really should come down to what pyVmomi supports (https://github.com/vmware/pyvmomi). 

"pyVmomi versions are marked vSphere_version-release . Pyvmomi maintains minimum backward compatibility with the previous _four_ releases of vSphere and it's own previous four releases. Compatibility with much older versions may continue to work but will not be actively supported."

This module was written and tested for pyVmomi 6.5, so if the above statement is true, then I would think the following vCenter versions are supported: 6.5, 6.0, 5.5, 5.1

I have personally only tested this module using pyVmomi 6.5+ on VCenter 6.0 update 3.

Glad you ran across this module, and I hope it works for you! I would be interested to hear what version(s) of vCenter you use this on and what your experience is.

**Comment by DustinTrap** [comment]
Thanks, that should more than cover my needs. Searching Google lead me here and we're going to give this a try. Thanks all the work getting here. It is appreciated!
