### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by hadfiiw** [napalm255/ansible-vmware_drs#63]
Sorry for the lame question but how to I install this module into my environment?  It is not part of the base Ansible modules, correct?

Thanks

**Comment by napalm255** [comment]
Simply create a "library" directory in you ansible project and place the "vmware_drs.py". The repo itself is laid out in a similar fashion so you can look at "test.yml" as an example.

**Comment by hadfiiw** [comment]
Thanks!  That worked.  Appreciate the help (and the module!)
